### ISSUE TITLE
Package a new release with current updates/commits

### ISSUE THREAD

**Issue by abien** [plesk/centos2alma#108]
If you could find the time to package a new release, that would be great. The download [centos2alma-0.1.0.zip](https://github.com/plesk/centos2alma/releases/download/v0.1.0/centos2alma-0.1.0.zip) is lots of commits behind current master.

I would like to do more testing in the coming weeks and i'd like to do that with the most recent version of the toolset.
Thanks,

PS: Or supply instructions on how to get from `git clone` to `./executable script` and we can do it ourselves.

**Comment by SandakovMM** [comment]
New release [is ready](https://github.com/plesk/centos2alma/releases/tag/v0.2.0)

About build instruction. I'm researching a way to provide docker container for build to make build as simple as possible.
