### ISSUE TITLE
NODE JS ISSUE 

### ISSUE THREAD

**Issue by AzamWahid** [plesk/centos2alma#119]
Experiencing a issue with #Plesk Whenever I add a subdomain, the Node.js feature goes down, leaving me with a blank screen. This problem started happening recently, affecting both existing subdomains and new ones. Need urgent help to get this resolved.

**Comment by SandakovMM** [comment]
Could you please provide more detailed steps to reproduce (STR)? For example:
1. Start with a CentOS 7 instance that has two domains configured.
2. Use the conversion tool to convert the instance to AlmaLinux 8.
3. After the conversion is complete, add a subdomain to one of the domains.
4. Encounter a problem with Node.js.

Am I understanding the steps correctly?

Additionally, could you please provide the feedback archive? You can retrieve it by running the command centos2alma --prepare-feedback.

**Comment by AzamWahid** [comment]
I think I open this issue in wrong place
sorry
