### ISSUE TITLE
After the first reboot, the ETA in "monitoring" is exceeded and produced a false positive warning

### ISSUE THREAD

**Issue by Bitpalast** [plesk/centos2alma#126]
After the first reboot, the ETA in the monitoring (--monitor) is exceeded. For a very short moment, a message can be seen that the process might be stuck and the user ought to check the logs. However, that message is overwritten with stars shortly after, so when a user is not highly attentive and waiting on that message, he can easily miss it an only see the red stars. When running --status, the same stars are shown. The user is left with no information how to proceed.
![grafik](https://github.com/plesk/centos2alma/assets/18143119/03419e62-6959-4a8d-8653-407f4030010b)

Actually, after checking the log, everything was good, the server simply needed more time to finish the task. It completed the installation and rebooted the 2nd time.

Suggestion for improvement: When the monitor/status messages are shown, the important part that recommends to check the log file should stay visible. Overwriting it with stars, especially red stars, leads the user into thinking that something is terribly wrong and gives no information where to check further.

**Comment by SandakovMM** [comment]
I have made some modifications to the "exceed" message to enhance clarity and encourage checking the log file. Related PR is #129
