### ISSUE TITLE
MariaDB 10.11 repo url not valid

### ISSUE THREAD

**Issue by m-witt** [plesk/centos2alma#136]
MariaDB 10.11 cannot be upgraded / reinstalled due to a broken link : 

`2023-08-28 15:32:49,519 - INFO - - Status code: 404 for http://mirror.mariadb.org/yum/10.11/centos8-amd64/repodata/repomd.xml (IP: 162.55.42.214) 
2023-08-28 15:32:49,522 - INFO - Error: Failed to download metadata for repo 'alma-mariadb': Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried`

pre-upgrade repo file : 
```
[root@abc123~]# cat /etc/yum.repos.d/mariadb.repo
# MariaDB 10.11 CentOS repository list - created Mon Jul  3 15:53:55 CEST 2023
# http://downloads.mariadb.org/mariadb/repositories/
[mariadb]
name = MariaDB
baseurl = http://yum.mariadb.org/10.11/centos7-amd64
module_hotfixes=1
gpgkey=https://yum.mariadb.org/RPM-GPG-KEY-MariaDB
gpgcheck=1
```

The mariadb-repo doesn't seem to have a link to the specific subdirectory for 10.11 (10.10 and below does) : 
`http://mirror.mariadb.org/yum/10.11/centos8-amd64/repodata/repomd.xml`

It should probably point to this : 
`http://mirror.mariadb.org/yum/10.11/centos/8/x86_64/repodata/repomd.xml`

As fas as i understand the conversion happens [here](https://github.com/plesk/centos2alma/blob/master/common/leapp_configs.py#L70) while called [here](https://github.com/plesk/centos2alma/blob/master/actions/mariadb.py#L71)

[centos2alma_feedback.zip](https://github.com/plesk/centos2alma/files/12455604/centos2alma_feedback.zip)

**Comment by SandakovMM** [comment]
Thank you for getting in touch with us.

You are correct; the CentOS 8 path is no longer relevant since MariaDB 10.11. Therefore, we should use the "rhel8-amd64" path or the "centos/8/x86_64" path mentioned earlier.

**Comment by SandakovMM** [comment]
Moved to rhel8-* repositories from yum.mariadb.org. Related PR - #137
