### ISSUE TITLE
1.2.2 tries to install MariaDB 11.1 if 10.6 is already installed on C7

### ISSUE THREAD

**Issue by ManfredLan** [plesk/centos2alma#158]
After #152 was closed and 1.2.2 was released I tested the new script and promply ran into a new problem.
In case on a  CentOS7 server MariaDB 10.6 is already installed and properly upgraded, the script tries to install MariaDB 11.1 during the upgrade-process, which then fails, here a excerpt from the log, I attached also a feedback file:

2024-01-08 14:55:57,620 - INFO - file /usr/share/man/man8/mysqld.8.gz from install of MariaDB-server-10.6.16-1.el8.x86_64 conflicts with file from package MariaDB-server-compat-11.1.3-1.el8.noarch
2024-01-08 14:55:57,673 - ERROR - Command '['/usr/bin/yum', 'install', '--repo', 'alma-mariadb-main', '-y', 'MariaDB-client', 'MariaDB-server']' failed with return code 1
2024-01-08 14:55:57,673 - ERROR - Failed: update modern mariadb!. The reason: Command '['/usr/bin/yum', 'install', '--repo', 'alma-mariadb-main', '-y', 'MariaDB-client', 'MariaDB-server']' returned non-zero exit status 1.
2024-01-08 14:55:59,647 - ERROR - centos2alma process has been failed. Error: Failed: update modern mariadb!. The reason: Command '['/usr/bin/yum', 'install', '--repo', 'alma-mariadb-main', '-y', 'MariaDB-client', 'MariaDB-server']' returned non-zero exit status 1.

mariadb.repo contains only 10.6

Also, server did not reboot automatically and froze during the reboot.

I also tested with MariaDB 10.3 and there the update script worked fine.

You could create it by calling `[centos2alma_feedback.zip](https://github.com/plesk/centos2alma/files/13861686/centos2alma_feedback.zip)`.
The archive will help us investigate the problem better and faster.

**Comment by ManfredLan** [comment]
Upgrading to 10.5 resulted in the same result as having 10.6 installed. Server does not reboot properly and conflicts with MariaDB 10.5 are logged.

also except the 11.1 packages MariaDb was completely missing.
> 
> $dnf list installed | grep MariaDB
> MariaDB-client-compat.noarch                11.1.3-1.el8                                  @System           
> MariaDB-server-compat.noarch                11.1.3-1.el8                                  @System

**Comment by SandakovMM** [comment]
It seems that your instance was converted but failed to finish the process. The issue appears to be a conflict between mariadb 10.6 and mariadb 11.1, which is unexpected since mariadb 11.1 should not be present after the conversion is completed. I will investigate this on my end.
I believe you could potentially solve the issue by removing the `MariaDB-server-compat` package and running `./centso2alma --finish`.

**Comment by SandakovMM** [comment]
It seems that Leapp has introduced a new repository for Mariadb version 11.1 at /etc/leapp/files/vendors.d/mariadb.repo. However, we would rather update based on the currently installed version of Mariadb to avoid any database upgrade actions. I will explore options to prevent the use of the repository on our end.

**Comment by SandakovMM** [comment]
I've pinned versions of leapp packages in #159. Will check if it works and publish tomorrow if it does

**Comment by SandakovMM** [comment]
I've [published 1.2.3](https://github.com/plesk/centos2alma/releases/tag/v1.2.3). There should not be such problem in the new version.

**Comment by Bitpalast** [comment]
I've tested the conversion after the latest update of the centos2alma script version 1.2.3 coming from MariaDB 10.6 and it worked as expected without errors.

**Comment by ManfredLan** [comment]
I can confirm, in my tests 1.2.3 worked fine now, thank you.
