### ISSUE TITLE
incompatible with warden extension | masked spamassassin causes script to abort

### ISSUE THREAD

**Issue by abien** [plesk/centos2alma#160]
Script aborts with this message:
```
2024-01-11 23:21:24,680 - INFO - Failed to enable unit: Unit file /etc/systemd/system/spamassassin.service is masked.
2024-01-11 23:21:24,681 - ERROR - Command '['/usr/bin/systemctl', 'enable', 'spamassassin.service']' failed with return code 1
```

I assume spamassassin was masked by this extension: https://www.plesk.com/extensions/warden-anti-spam-virus-protection/
The masking causes the upgrade script to abort.

I don't know enough about the warden extension to suggest a good course of action. Maybe just print a warning in preflight and ask user to de-install the extension for the duration of the upgrade.

**Comment by SandakovMM** [comment]
Hmm, I couldn't reproduce the problem. Maybe some other extension add mask for spamassassin.service.
Don't you have a feedback archive, accidentally?

**Comment by abien** [comment]
Sorry, no. We have since upgraded said system successfully. Maybe this was something historic that cannot be reproduced with current versions.
Feel free to close. On the offchance that we experience this again i will collect and provide the archive.
