### ISSUE TITLE
Conversion Support for VPS inside Virtuozzo Containers

### ISSUE THREAD

**Issue by LazariPetru** [plesk/centos2alma#162]
Hi,

As an active user of Plesk, I have noted the instructions specifying that the conversion process is not supported inside containers, including Virtuozzo containers.

Understanding the importance of this limitation, I would like to express a concern shared by numerous users who predominantly utilize VPS servers instead of dedicated (particularly those within Virtuozzo containers).

It would be highly beneficial if there were plans to extend support for the conversion process within Virtuozzo containers. Is there any ongoing discussions or plans regarding this matter?

Many thanks,
Petru

**Comment by futureweb** [comment]
Please see https://github.com/plesk/centos2alma/issues/87

**Comment by LazariPetru** [comment]
Just saw it, closing as duplicated.
Thanks

**Comment by futureweb** [comment]
@LazariPetru alright, guess you should also comment on my Ticket #87 so Plesk sees there is more demand than only from our side ;-)
