### ISSUE TITLE
Do preparation checks...exec: "mysql": executable file not found in $PATH

### ISSUE THREAD

**Issue by IronButterfly** [plesk/centos2alma#163]
**Describe the bug**
After the first attempt to run the script, an error occurred with the dependencies of the libwebp7 package. 

STDERR:
No matches found for the following disable plugin patterns: subscription-manager
Repository extras is listed more than once in the configuration
Repository extras-source is listed more than once in the configuration
Warning: Package marked by Leapp to upgrade not found in repositories metadata: gpg-pubkey
RPM: warning: Generating 6 missing index(es), please wait...
Error: Transaction test error:
  file /usr/lib64/libwebp.so.7 from install of libwebp-1.0.0-9.el8_9.1.x86_64 conflicts with file from package libwebp7-1.0.3-2.el7.remi.x86_64
  file /usr/lib64/libwebpdecoder.so.3 from install of libwebp-1.0.0-9.el8_9.1.x86_64 conflicts with file from package libwebp7-1.0.3-2.el7.remi.x86_64
  file /usr/lib64/libwebpdemux.so.2 from install of libwebp-1.0.0-9.el8_9.1.x86_64 conflicts with file from package libwebp7-1.0.3-2.el7.remi.x86_64
  file /usr/lib64/libwebpmux.so.3 from install of libwebp-1.0.0-9.el8_9.1.x86_64 conflicts with file from package libwebp7-1.0.3-2.el7.remi.x86_64

2024-01-16 09:43:07.571 WARNING  PID: 29455 leapp.reporting: Stable Key report entry not provided, dynamically generating one - 44eb7c10807a57878b4cf4108a089a21a6db7727
2024-01-16 09:43:07.749 WARNING  PID: 29455 leapp.reporting: Stable Key report entry not provided, dynamically generating one - 44eb7c10807a57878b4cf4108a089a21a6db7727
2024-01-16 09:43:07.834 WARNING  PID: 29455 leapp.reporting: Stable Key report entry not provided, dynamically generating one - 44eb7c10807a57878b4cf4108a089a21a6db7727
2024-01-16 09:43:07.887 ERROR    PID: 29455 leapp: Upgrade workflow failed, check log for details

I tried to remove the confilict package using 

rpm -e --nodeps libwebp7 

and run the script again. But now I see an error like

# ./centos2alma
Do preparation checks...exec: "mysql": executable file not found in $PATH

Looks like mysql is gone.

What can I do now?
[Uploading centos2alma_feedback.zip…]()

**Feedback archive**
*Please attach a feedback archive to the bug report.*
You could create it by calling `centos2alma --prepare-feedback`.
The archive will help us investigate the problem better and faster.

**Comment by IronButterfly** [comment]
[Uploading centos2alma_feedback.zip…]()

**Comment by SandakovMM** [comment]
The problem with `exec: "mysql": executable file not found in $PATH` occurs because the Plesk database is turned off. We should not rely on the database so much, so I will investigate how we can resolve this.
In the meantime, you can use the temporary workaround by running: `systemctl start mariadb.service` (or mysql.service if you use mysql)

**Comment by IronButterfly** [comment]
Unfortunately it's not that simple... Your workaround doesn't work for the simple reason that all the database server packages were removed from the server, so there was simply nothing to start.
