### ISSUE TITLE
Keep SELinux configuration as is

### ISSUE THREAD

**Issue by Bitpalast** [plesk/centos2alma#168]
**Is your feature request related to a problem? Please describe.**
The SELinux configuration is changed to "permissive" during the conversion process, even if it was previously "disabled" on the system from where we start out. A change of an SELinux configuration always triggers an autorelabelling routine during the reboot. Autorelabelling can take a very long time. For example to autorelabel just the essential OS directories it will typically take around 4 to 7 minutes, but if /var/www and /home are not excluded and contain many files, i can take a very long time, for example 90 minutes when a user has hundreds of domains on the server. 

**Describe the solution you'd like**
If SELinux is "disabled", it should stay "disabled". If it is in "permissive" mode it should stay in "permissive" mode. If it was set to "enforcing", then it should be set to "enforcing" after conversion, too. 

**Describe alternatives you've considered**
If an existing state cannot be preserved, e.g. because the whole component is exchanged, and an autorelabelling is unavoidable, it could be advised to create /etc/selinux/fixfiles_exclude_dirs with two lines /home and /var/www so that the time needed for the process is reduced to a minimum.
Or:
In the instructions users should be made aware that during a boot phase autorelabelling might kick-in and cause a long delay. Else they might think the system hangs and attempt a full reinstall or restore although the system just needed more time for the process.

**Additional context**
n/a
![2024-01-30_14-40-36](https://github.com/plesk/centos2alma/assets/18143119/8454b496-836e-4f86-b8bb-8e28e90e006e)

**Comment by SandakovMM** [comment]
Great point, thank you. We will take a look at it.

**Comment by SandakovMM** [comment]
I checked it again, and we should keep selinux disabled, as we only change the status if [selinux is in "Enforcing" state](https://github.com/plesk/centos2alma/blob/master/actions/common.py#L84-L88).
Could you please please share the feedback archive and the output of the `getenforce` utility?

**Comment by Bitpalast** [comment]
Unfortunately the previous test installation is already gone, making room for a new one. If I encounter the same issue again, I'll send a log.

**Comment by SandakovMM** [comment]
It has been observed that selinux will initiate a relabel on any server startup even if it is disabled. This behavior can be disabled in the grub configuration. But in case of conversion it should also be also disabled before the final stage of the conversion is completed.
I think we should not disable it on our end (inside centos2alma) because we cannot be certain if a customer decides to enable selinux later. If they do, it will be difficult to determine the exact cause of issues with relabeling on startup and where they stem from.
