### ISSUE TITLE
[Minor] Each interrupted script run duplicates the /etc/motd messages

### ISSUE THREAD

**Issue by Bitpalast** [plesk/centos2alma#169]
**Describe the bug**
Found a very minor UX bug: If a conversion phase is interrupted and that conversion phase writes a message to /etc/motd, it appends /etc/motd with the same message on the next script execution. In a test with two deliberate script execution interruptions before the first reboot this resulted in three such conversion messages (see screenshot). 

![2024-01-31_10-13-55](https://github.com/plesk/centos2alma/assets/18143119/190d80d2-b4f6-4ce8-9a71-0917ddc8c912)

When the conversion has finished, the duplicate entries are correctly replaced by a single /etc/motd message that informs the user that the conversion has finished.

**Comment by SandakovMM** [comment]
The problem should be fixed by #173
