### ISSUE TITLE
DH keys too small after conversion --> Dovecot does not allow logins --> Suggest auto-fix after conversion

### ISSUE THREAD

**Issue by Bitpalast** [plesk/centos2alma#181]
**Is your feature request related to a problem? Please describe.**
After the conversion of a server, Dovecot email login was no longer possible due to short keys used on the server.

**Describe the solution you'd like**
https://support.plesk.com/hc/en-us/articles/12377016572439-Unable-to-log-in-to-Roundcube-webmail-or-using-email-client-on-Plesk-server-Can-t-load-DH-parameters-dh-key-too-small

\# plesk sbin sslmng --service dovecot --strong-dh --dhparams-size=2048
(fixed it)

**Describe alternatives you've considered**
n/a

**Additional context**
Maybe it would be good if the script could check whether the issue described in the KB article exists after a conversion and then automatically run the dhparams-size command to increase the key size.

**Comment by SandakovMM** [comment]
The problem should be fixed in #191.
