### ISSUE TITLE
ERROR while Converting a CentOS 7 server with Plesk to AlmaLinux 8

### ISSUE THREAD

**Issue by silikonski** [plesk/centos2alma#187]
### ****Describe the bug**
BUG: Converting processes stopped on later stage.

###############   LOG File  centos2alma  ################
INFO - Running transaction check
INFO - Transaction check succeeded.
INFO - Running transaction test
INFO - The downloaded packages were saved in cache until the next successful transaction.
INFO - You can remove cached packages by executing 'dnf clean packages'.
INFO - STDERR:
INFO - Repository extras is listed more than once in the configuration
INFO - Repository extras-source is listed more th2024-02-28 17:59:46.481 ERROR    PID: 21022 leapp: Upgrade workflow failed, check log for details
INFO - an once in the configuration
INFO - Warning: Package marked by Leapp to upgrade not found in repositories metadata: gpg-pubkey
INFO - RPM: warning: Generating 6 missing index(es), please wait...
INFO - Error: Transaction test error:
INFO - file /usr/lib64/libwebp.so.7 from install of libwebp-1.0.0-9.el8_9.1.x86_64 conflicts with file from package libwebp7-1.0.3-2.el7.remi.x86_64
INFO - file /usr/lib64/libwebpdecoder.so.3 from install of libwebp-1.0.0-9.el8_9.1.x86_64 conflicts with file from package libwebp7-1.0.3-2.el7.remi.x86_64
INFO - file /usr/lib64/libwebpdemux.so.2 from install of libwebp-1.0.0-9.el8_9.1.x86_64 conflicts with file from package libwebp7-1.0.3-2.el7.remi.x86_64
INFO - file /usr/lib64/libwebpmux.so.3 from install of libwebp-1.0.0-9.el8_9.1.x86_64 conflicts with file from package libwebp7-1.0.3-2.el7.remi.x86_64
INFO - file /usr/lib64/libzip.so.5 from install of libzip-1.5.1-2.module_el8.3.0+2010+7c76a223.x86_64 conflicts with file from package libzip5-1.10.1-1.el7.remi.x86_64
INFO - file /usr/lib64/libytnef.so.0.0.0 from install of ytnef-2.1.2-1.el8.x86_64 conflicts with file from package libytnef-1.5-14.el7.x86_64
============================================================
ERROR - Command '['/usr/bin/leapp', 'upgrade']' failed with return code 1
ERROR - Failed: doing the conversion!. The reason: Command '['/usr/bin/leapp', 'upgrade']' returned non-zero exit status 1.
ERROR - centos2alma process has been failed. Error: Failed: doing the conversion!. The reason: Command '['/usr/bin/leapp', 'upgrade']' returned non-zero exit status 1.
ERROR - module 'common.src.log' has no attribute 'error'
ERROR - Please fix noted problems before proceed the conversion
ERROR - module 'common.src.log' has no attribute 'error'
ERROR - Please fix noted problems before proceed the conversion
ERROR - Required pre-conversion condition checking if distro is AlmaLinux8 not met:
################  TXT File  leapp-report  ###################
----------------------------------------
Risk Factor: medium
Title: memcached service is using default configuration
Summary: memcached in RHEL8 listens on loopback only and has UDP port disabled by default
Key: 336e6b0960fdd7dec80b4243ce1a153cb7d0bccf
----------------------------------------
Risk Factor: medium
Title: Module pam_pkcs11 will be removed from PAM configuration
Summary: Module pam_pkcs11 was surpassed by SSSD and therefore it was removed from RHEL-8. Keeping it in PAM configuration may lock out the system thus it will be automatically removed from PAM configuration before upgrading to RHEL-8. Please switch to SSSD to recover the functionality of pam_pkcs11.
Remediation: [hint] Configure SSSD to replace pam_pkcs11
Key: bf47e7305d6805e8bbeaa7593cf01e38030c23f3
----------------------------------------
Risk Factor: medium
Title: chrony using default configuration
Summary: default chrony configuration in RHEL8 uses leapsectz directive, which cannot be used with leap smearing NTP servers, and uses a single pool directive instead of four server directives
Key: c4222ebd18730a76f6bc7b3b66df898b106e6554
----------------------------------------
Risk Factor: medium
Title: spamc no longer allows specifying the TLS version and no longer supports SSLv3
Summary: spamc no longer allows using the "--ssl" option with an argument specifying the TLS version - the option can only be used without an argument. Also, spamc no longer supports SSLv3.
Remediation: [hint] Please update your scripts and configuration, if there are any.
Key: 2c9706965164a658b1f1443d5d24b1fe3e9ec4d2
----------------------------------------
Risk Factor: medium
Title: spamd no longer allows specifying the TLS version and no longer supports SSLv3
Summary: spamd no longer accepts the --ssl-version option and no longer supports SSLv3.
Remediation: [hint] Please update your scripts and configuration, if there are any.
Key: 174eb9ad0aed3013f829e892ee753967058f51d5
----------------------------------------
Risk Factor: medium
Title: The type of the spamassassin systemd service has changed
Summary: The type of spamassassin.service has been changed from "forking" to "simple". The spamassassin sysconfig file will be updated.
Key: 3ed08dd692315c1f736daf2a0f533f6ebca70cc4
----------------------------------------
Risk Factor: low
Title: Grep has incompatible changes in the next major version
Summary: If a file contains data improperly encoded for the current locale, and this is discovered before any of the file's contents are output, grep now treats the file as binary.
The 'grep -P' no longer reports an error and exits when given invalid UTF-8 data. Instead, it considers the data to be non-matching.
In locales with multibyte character encodings other than UTF-8, grep -P now reports an error and exits instead of misbehaving.
When searching binary data, grep now may treat non-text bytes as line terminators. This can boost performance significantly.
The 'grep -z' no longer automatically treats the byte '\200' as binary data.
Context no longer excludes selected lines omitted because of -m. For example, 'grep "^" -m1 -A1' now outputs the first two input lines, not just the first line.

Remediation: [hint] Please update your scripts to be compatible with the changes.
Key: 94665a499e2eeee35eca3e7093a7abe183384b16
----------------------------------------
Risk Factor: low
Title: sa-update no longer supports SHA1 validation
Summary: sa-update no longer supports SHA1 validation of filtering rules, SHA256/SHA512 validation is done instead. This may affect you if you are using an alternative update channel (sa-update used with option --channel or --channelfile), or if you install filtering rule updates directly from files (sa-update --install).
Key: 5f94c35aab24e5ce2033c8bec5b83902caedecc3
----------------------------------------
Risk Factor: low
Title: The subscription-manager release is going to be kept as it is during the upgrade
Summary: The upgrade is executed with the --no-rhsm option (or with the LEAPP_NO_RHSM environment variable). In this case, the subscription-manager will not be configured during the upgrade. If the system is subscribed and release is set already, you could encounter issues to get RHEL content using DNF/YUM after the upgrade.
Remediation: [hint] Set the new release (or unset it) after the upgrade using subscription-manager: subscription-manager release --set 8.6
Key: 01986584e27e85ea18929586faf614eee011a121
----------------------------------------
Risk Factor: info
Title: SElinux relabeling will be scheduled
Summary: SElinux relabeling will be scheduled as the status is permissive/enforcing.
Key: 8fb81863f8413bd617c2a55b69b8e10ff03d7c72
----------------------------------------
Risk Factor: info
Title: Current PAM and nsswitch.conf configuration will be kept.
Summary: There is a new tool called authselect in RHEL8 that replaced authconfig. The upgrade process was unable to find an authselect profile that would be equivalent to your current configuration. Therefore your configuration will be left intact.
Key: 40c4ab1da4a30dc1ca40e543f6385e1336d8810c**

**Comment by SandakovMM** [comment]
Hello,
It appears that the server has the following non-standard repository packages installed:
- libwebp7
- libzip5
- libytnef

I believe it will be enough to remove them to proceed the conversion.
I will add them to the list of re-installable conflict packages

**Comment by SandakovMM** [comment]
The problem should be fixed by #192. Please find attached zip archive with new centos2alma build - 
[centos2alma.zip](https://github.com/plesk/centos2alma/files/14490426/centos2alma.zip)

**Comment by silikonski** [comment]
Thank you for your replays, I will remove all of this non-standard repository and try new centos2alma build. I hope it will work.

**Comment by silikonski** [comment]
I almost succeeded nut on the very end I got this errors:

ERROR - Command '['/usr/bin/leapp', 'upgrade']' failed with return code 1
ERROR - Failed: doing the conversion!. The reason: Command '['/usr/bin/leapp', 'upgrade']' returned non-zero exit status 1.
ERROR - centos2alma process has been failed. Error: Failed: doing the conversion!. The reason: Command '['/usr/bin/leapp', 'upgrade']' returned non-zero exit status 1.

Any idea? Thank you.

**Comment by SandakovMM** [comment]
Could you please provide a feedback archive

**Comment by silikonski** [comment]
> Could you please provide a feedback archive

It is the zip file I attached in previous post, a got that file bu executing this:
`./centos2alma --prepare-feedback`

**Comment by silikonski** [comment]
Ok, I probably downloaded wrong file. I will do the process again and get the right file. I had to recreate server form image so the feedback file is not there any more. Thank you for your patient.

**Comment by silikonski** [comment]
Ok, here is the feedback file. I hope it will help.
[centos2alma_feedback.zip](https://github.com/plesk/centos2alma/files/14641126/centos2alma_feedback.zip)

**Comment by silikonski** [comment]
> > It is the zip file I attached in previous post, a got that file bu executing this:
> 
> Hm, The active you mentioned contains the script itself as far as I could see

I uploaded few days ago new file can you please check? Thank you.

**Comment by SandakovMM** [comment]
Apologies for the delay. I noticed that there are conflicting packages installed on your server, which is causing the conversion to fail:
```
2024-03-18 19:11:57,531 - INFO - file /usr/lib64/libwebp.so.7 from install of libwebp-1.0.0-9.el8_9.1.x86_64 conflicts with file from package libwebp7-1.0.3-2.el7.remi.x86_64
2024-03-18 19:11:57,531 - INFO - file /usr/lib64/libwebpdecoder.so.3 from install of libwebp-1.0.0-9.el8_9.1.x86_64 conflicts with file from package libwebp7-1.0.3-2.el7.remi.x86_64
2024-03-18 19:11:57,531 - INFO - file /usr/lib64/libwebpdemux.so.2 from install of libwebp-1.0.0-9.el8_9.1.x86_64 conflicts with file from package libwebp7-1.0.3-2.el7.remi.x86_64
2024-03-18 19:11:57,531 - INFO - file /usr/lib64/libwebpmux.so.3 from install of libwebp-1.0.0-9.el8_9.1.x86_64 conflicts with file from package libwebp7-1.0.3-2.el7.remi.x86_64
2024-03-18 19:11:57,531 - INFO - file /usr/lib64/libzip.so.5 from install of libzip-1.5.1-2.module_el8.3.0+2010+7c76a223.x86_64 conflicts with file from package libzip5-1.10.1-1.el7.remi.x86_64
2024-03-18 19:11:57,531 - INFO - file /usr/lib64/libytnef.so.0.0.0 from install of ytnef-2.1.2-1.el8.x86_64 conflicts with file from package libytnef-1.5-14.el7.x86_64
```
This packages should be removed on preupgrade stage by [centos2alma v1.2.4](https://github.com/plesk/centos2alma/releases/tag/v1.2.4)

**Comment by silikonski** [comment]
Thank you for the answer. What do you suggest, to remove them manually?
As you earlier suggested a did remove following packages before upgrade, but I still get the error.

    libwebp7
    libzip5
    libytnef

**Comment by SandakovMM** [comment]
I recommend trying to convert using the new version of centos2alma (v1.2.4).
