### ISSUE TITLE
Preserve Roundcube webmail configuration file content

### ISSUE THREAD

**Issue by Bitpalast** [plesk/centos2alma#195]
**Is your feature request related to a problem? Please describe.**
When Roundcube is reinstalled for Alma, the existing /usr/share/psa-roundcube/config/config.inc.php configuration file is overwritten by a default file.

**Describe the solution you'd like**
Store the original /usr/share/psa-roundcube/config/config.inc.php settings in the first conversion phase, restore them in the last phase.

**Describe alternatives you've considered**
Copy the file manually before conversion, restore the content manually afterwards.

**Comment by SandakovMM** [comment]
I have added a feature to save the config.inc.php file as a backup in the /usr/local/psa/var/centos2alma directory (#377).
The newer Plesk versions use the /usr/share/psa-roundcube/config/config.local.php file for storing customizations. If this file does not exist, centos2alma will create it for you and store your customizations there. However, if the file already exists, I decided it would be safer to simply create a backup.
