### ISSUE TITLE
Preserve Dovecot /etc/dovecot/dovecot.conf configuration file

### ISSUE THREAD

**Issue by Bitpalast** [plesk/centos2alma#196]
**Is your feature request related to a problem? Please describe.**
On the Dovecot reinstallation during the conversion, the /etc/dovecot/dovecot.conf is overwritten with a default file. Normally it is advised not to have any custom tweaks in that file, but this does not work reliably for the "auth_mechanisms" setting. Removal of digest-md5 from that line is crucial, as otherwise some mail apps only login after a second or third attempt. This triggers Fail2Ban (one false login per login attempt), and this again blocks the user. For that reason, users have asked to have digest-md5 removed by default, e.g. in https://plesk.uservoice.com/forums/184549-feature-suggestions/suggestions/41190802-remove-digest-md5-from-dovecot-and-postfix-configs. Unfortunately this hasn't made it into the Plesk default setup yet, so the only way to reliably remove digest-md5 is to remove it from the dovecot.conf file. It is not sufficient to create an additional configuration file for that (tests had shown it just won't work reliably). This means that users depend on preservation of their /etc/dovecot/dovecot.conf file.

**Describe the solution you'd like**
Save /etc/dovecot/dovecot.conf in phase 1 of conversion, restore it in the last phase.

**Describe alternatives you've considered**
Save it manually, restore it manually.

**Comment by SandakovMM** [comment]
Should be fixed by #207, #208. Please find attached centos2alma - [centos2alma.zip](https://github.com/plesk/centos2alma/files/14614075/centos2alma.zip)
