### ISSUE TITLE
[Minor] Status bar in finish phase is distorted when time limit is exceeded

### ISSUE THREAD

**Issue by Bitpalast** [plesk/centos2alma#211]
**Describe the bug**
When the anticipated runtime limit is exceeded, the status bar changes to red, but it only shows some asterisk and other characters. The user cannot see what's going on.
![2024-03-16_18-02-31](https://github.com/plesk/centos2alma/assets/18143119/e2e71ad5-cc7a-44df-8909-a07ab1068130)

**Desired solution**
Show a readible message. It would be even better if the status bar displayed the say "last ten lines" of /var/log/plesk/centos2alma.log as they are updated (like the "F" option in a display of "less"), so that the user can see whether the script is still doing something. But even that might not be adequate, as for example when a httpdmng reconfiguration is going on, the log doesn't move either although sw-engine and httpdmng are very active.

**Comment by SandakovMM** [comment]
The problem should be fixed by #374
