### ISSUE TITLE
Migration step is not moving forward 

### ISSUE THREAD

**Issue by jwnmohan** [plesk/centos2alma#229]
Hi Team,

I am running CentOS7.9 with plesk 18.0.52 

~  cat /etc/redhat-release
CentOS Linux release 7.9.2009 (Core)

~  plesk -v
Product version: Plesk Obsidian 18.0.52.3
     OS version: CentOS 7.9.2009 x86_64
     Build date: 2023/05/16 12:00
       Revision: a3b74dbc9de2e47afd4e532d02fa7759b29d3fa5
       
       When i tired to perform the migration from centos7toalmalinux8 is stopping with below note 
       
     ~  ./centos2alma
Do preparation checks...~

Please suggest how to proceed further. I have changed the permission as well mention in the steps

**Comment by SandakovMM** [comment]
Could you please call centos2alma with `--verbose` option. After is stopped provide a feedback archive that could be created by `centos2alma --prepare-feedback`

**Comment by SandakovMM** [comment]
Unfortunately, I cannot continue the investigation without the feedback archive. I have resolved similar issues in previous releases, so this issue might already be fixed.

You are welcome to reopen the issue with the feedback archive if you will be able reproduce the problem on the latest centos2alma version.
