### ISSUE TITLE
Centos7.9 to AlmaLinux8 migration issue and got stuck 

### ISSUE THREAD

**Issue by jwnmohan** [plesk/centos2alma#232]
H Team,

I have an environment running Centos7 with plesk 18.0.52 , When i tried to perform the migration to AlmaLinux8 i got below error , But my packages and patches are up to date. Kindly advise 

~  ./centos2alma
Required pre-conversion condition checking if all packages are up to date not met:
        There are packages which are not up to date. Call `yum update -y && reboot` to update the packages.

~  yum update -y
Loaded plugins: fastestmirror, rhnplugin
Loading mirror speeds from cached hostfile
 * base: download.cf.centos.org
 * epel: level66.mm.fcix.net
 * extras: download.cf.centos.org
 * updates: download.cf.centos.org
No packages marked for update

**Comment by jwnmohan** [comment]
[centos2alma_feedback.zip](https://github.com/plesk/centos2alma/files/14904524/centos2alma_feedback.zip)
Please find the attached feedback log

**Comment by SandakovMM** [comment]
Could you please provide output of the `/usr/bin/yum check-update`?

**Comment by jwnmohan** [comment]
~  /usr/bin/yum check-update
Loaded plugins: fastestmirror, rhnplugin
There was an error communicating with CLN.
CLN support will be disabled.
Error communicating with server. The message was:
com.cloudlinux.clos.domain.exceptions.xmlrpc.ClnXmlRpcException: (=_=) Invalid System Credentials. Cannot parse request or identify server. Please, run registration again.
Loading mirror speeds from cached hostfile
 * base: download.cf.centos.org
 * epel: d2lzkl7pfhq30w.cloudfront.net
 * extras: download.cf.centos.org
 * updates: download.cf.centos.org
~

**Comment by SandakovMM** [comment]
> There was an error communicating with CLN.
It seems that there are issues with the Cloud Linux repositories causing the problem.

**Comment by jwnmohan** [comment]
I dont have any cloudlinux repo , configured with it 

repo id                                                         repo name                                                                              status
PLESK_17_PHP74                                                  PHP 7.4                                                                                    36
PLESK_17_PHP80                                                  PHP 8.0                                                                                    34
PLESK_17_PHP82                                                  PHP 8.2                                                                                    34
PLESK_18_0_52-extras                                            PLESK_18_0_52 extras                                                                       35
base/7/x86_64                                                   CentOS-7 - Base                                                                        10,072
epel/x86_64                                                     Extra Packages for Enterprise Linux 7 - x86_64                                         13,798
extras/7/x86_64                                                 CentOS-7 - Extras                                                                         526
plesk-ext-grafana                                               grafana extension repository                                                                2
plesk-ext-panel-migrator                                        panel-migrator extension repository                                                        16
plesk-ext-ruby                                                  ruby extension repository                                                                  15
plesk-ext-site-import                                           site-import extension repository                                                           16
updates/7/x86_64                                                CentOS-7 - Updates                                                                      5,802
repolist: 30,386

**Comment by jwnmohan** [comment]
Ok . Thanks , But i have tried in other server , Where we got this error.

2024-04-08 15:22:04,713 - INFO - Checking for installed packages...
2024-04-08 15:22:05,683 - INFO - ERROR: No products are installed yet. Use the 'install' command to install one first.
2024-04-08 15:22:05,689 - INFO - exit status 1
2024-04-08 15:22:05,690 - ERROR - Command '['/usr/sbin/plesk', 'installer', 'update']' failed with return code 1
2024-04-08 15:22:05,690 - ERROR - Failed: updating plesk!. The reason: Command '['/usr/sbin/plesk', 'installer', 'update']' returned non-zero exit status 1.
2024-04-08 15:22:06,731 - ERROR - centos2alma process has been failed. Error: Failed: updating plesk!. The reason: Command '['/usr/sbin/plesk', 'installer',
'update']' returned non-zero exit status 1.

It doesnt have any Cloudlinux repo , 

~  /usr/bin/yum check-update
Loaded plugins: fastestmirror
Loading mirror speeds from cached hostfile
 * base: download.cf.centos.org
 * epel: d2lzkl7pfhq30w.cloudfront.net
 * extras: download.cf.centos.org
 * updates: download.cf.centos.org
~

REPO works fine ,

~  yum repolist
Loaded plugins: fastestmirror
Loading mirror speeds from cached hostfile
 * base: download.cf.centos.org
 * epel: d2lzkl7pfhq30w.cloudfront.net
 * extras: download.cf.centos.org
 * updates: download.cf.centos.org
repo id                                                         repo name                                                                              status
PLESK_17_PHP74                                                  PHP 7.4                                                                                    36
PLESK_17_PHP80                                                  PHP 8.0                                                                                    34
PLESK_17_PHP82                                                  PHP 8.2                                                                                    34
PLESK_18_0_52-extras                                            PLESK_18_0_52 extras                                                                       35
base/7/x86_64                                                   CentOS-7 - Base                                                                        10,072
epel/x86_64                                                     Extra Packages for Enterprise Linux 7 - x86_64                                         13,798
extras/7/x86_64                                                 CentOS-7 - Extras                                                                         526
plesk-ext-grafana                                               grafana extension repository                                                                2
plesk-ext-panel-migrator                                        panel-migrator extension repository                                                        16
plesk-ext-ruby                                                  ruby extension repository                                                                  15
plesk-ext-site-import                                           site-import extension repository                                                           16
updates/7/x86_64                                                CentOS-7 - Updates                                                                      5,802
repolist: 30,386
~

Can you please suggest with this one ?

**Comment by SandakovMM** [comment]
As for the fix from the centos2alma side, we will now set restrictions to at least 18.0.55 for the time being.
Actually, we designates one oldest Plesk version as outdated each release. So the solution is not ideal. It might even be necessary for centos2alma to require the installation of the latest version of Plesk, but I am not entirely satisfied with this approach

**Comment by jwnmohan** [comment]
Thanks a lot for your reply , 

I have updated the plesk to 18.0.60 and then the migration started and it got failed in leapp preupgrade stage of 6 with below list of problem as attached . Kindly advise with this to proceed further. 
[leapp_error.txt](https://github.com/plesk/centos2alma/files/14956912/leapp_error.txt)

**Comment by jwnmohan** [comment]
Please find the attached log 
[centos2alma.log](https://github.com/plesk/centos2alma/files/14959410/centos2alma.log)

**Comment by SandakovMM** [comment]
It looks like Leapp is trying to retrieve some packages from the el7 Plesk repositories, which seems unusual (should from el8). I have successfully converted my instance with Plesk 18.0.60 without any problems, so it doesn't seem to be an issue specific to this version of Plesk, as I initially thought.

I suspect that the problem lies somewhere in Leapp's configurations. Could you please provide a feedback archive from this host?

**Comment by SandakovMM** [comment]
I think I have found the cause of the issue with the `plesk installed update` that you mentioned earlier. It seems that if plesk was originally installed from the autoinstall-archive repository, the conversion process will get stuck because it relies on the currently set repositories. I will fix it.

**Comment by SandakovMM** [comment]
We have included a pre-checker that prevents the conversion if Plesk was installed from the archive repository. To continue with the conversion in this situation, we suggest updating Plesk to the latest version. The related change is #354.
