### ISSUE TITLE
Usage after EOL date of CentOS7?

### ISSUE THREAD

**Issue by ManfredLan** [plesk/centos2alma#247]
Hi,

since there does not seem to be a specific information and a customer approached me with this question: Will it be possible to use this script after June 2024? 
I guess that depends a lot on how the original LEAPP developers will handle it?

Thanks in advance.

**Comment by SandakovMM** [comment]
Hello @ManfredLan,

> Will it be possible to use this script after June 2024?
> I guess that depends a lot on how the original LEAPP developers will handle it?

You're right. Our reliance on LEAPP's functionality for reinstalling packages means we anticipate that the original LEAPP developers will address the EOL issue.

From the perspective of Plesk. We typically move the last available version for EOLed distros into the archive.plesk.autoinstall repository. The movement will require some extra work on the centos2alma side.

However, from a user's perspective, there shouldn't be a problem using the tool after the EOL. This is our current plan.
