### ISSUE TITLE
Plesk administrator receives mails: Cron error: /usr/sbin/ntpdate: not found

### ISSUE THREAD

**Issue by FranSarr** [plesk/centos2alma#265]
After updating my plesk server from centos 7 to alma 8 i receive the following email message from Cron Daemon:
<root@mail> /usr/sbin/ntpdate -b -s 3.pool.ntp.org 
/bin/sh: /usr/sbin/ntpdate: No such file or directory

The error message you're seeing indicates that the ntpdate command is no longer available on your system after the upgrade from CentOS 7 to AlmaLinux 8. In AlmaLinux 8, ntpdate has been deprecated in favor of chrony, which is the recommended way to keep your system time synchronized.

To resolve this issue, you can either install the ntpdate package if it is still available, or better yet, switch to using chrony. 
This can be done by installing https://www.plesk.com/extensions/ntp-timesync/ extension and deleting the old ntpdate command from the cron job.

**Comment by SandakovMM** [comment]
I believe the same problem described in #182

**Comment by FranSarr** [comment]
Absolutelly
Thanks

Francisco Sarrias
Telecom Engineer
E: ***@***.***
P: +34 607 287953
W:https://www.linkedin.com/in/fsarrias/
