### ISSUE TITLE
/usr/bin/leapp preupgrade failed

### ISSUE THREAD

**Issue by L1Biznetgio** [plesk/centos2alma#272]
**Describe the bug**
I am migrating from CentOS 7 to AlmaLinux 8 and encountering issues with the attached feedback. The kernel I am using is: kernel-3.10.0-1160.118.1.el7.x86_64.

Please review the attached feedback and help me resolve this issue.

Thank you.

**Feedback archive**
[centos2alma_feedback.zip](https://github.com/user-attachments/files/15569728/centos2alma_feedback.zip)

**Comment by SandakovMM** [comment]
The error message "Multiple devel kernels installed" suggests that you have multiple "kernel-devel" packages installed.
You can find a list of these packages using the command `yum list installed | grep "kernel-devel"`.
The Leapp sources indicate that you need only one "kernel-devel" package installed to proceed with the conversion. So you have to remove all "kernel-devel" packages except one.
I will create a similar pre-checker for centos2alma to ensure the conversion does not start in this situation.

**Comment by SandakovMM** [comment]
I have added a pre-checker that will prevent the conversion if more than one kernel-devel package is installed. See the change in #320.
