### ISSUE TITLE
Prevent loss of emails due to Amavis removal

### ISSUE THREAD

**Issue by stijneikelboom** [plesk/centos2alma#288]
**Is your feature request related to a problem? Please describe.**
The [Plesk Email Security](https://www.plesk.com/plesk-email-security/) extension uses Amavis as a content filter behind Postfix. The conversion process removes Amavis, but leaves the Postfix config as is. When the server comes back online, routing mails to Amavis fails, leading to the unrecoverable loss of messages.

**Describe the solution you'd like**
During conversion, either:
- Remove or comment the line `content_filter = smtp-amavis:[127.0.0.1]:10024` in `/etc/postfix/main.cf`, if present.
- Reinstall and enable Amavis when Plesk Email Security is installed on the server.

**Describe alternatives you've considered**
Manually reinstall Amavis or the entire Plesk Email Security extension directly after the conversion.

**Comment by SandakovMM** [comment]
I have added the reinstallation of the Amavis antivirus in #321.
I also discovered that AlmaLinux 8 needs more RAM to ensure proper operation. Therefore, I added a pre-check to verify available RAM to prevent conversion if there's uncertainty about Amavis functioning afterward.
