### ISSUE TITLE
utf8 decode error during leapp system_facts preupgrade step

### ISSUE THREAD

**Issue by reashetyrr** [plesk/centos2alma#305]
**Describe the bug**
When running the centos2alma everything seems to work fine until we get to the leapp preupgrade step, here it gives a unicodedecodeerror.

**Feedback archive**

[centos2alma_feedback.zip](https://github.com/user-attachments/files/16235595/centos2alma_feedback.zip)

**Comment by SandakovMM** [comment]
It seems that Leapp has failed to parse the kernel modules information.
Could you please provide a list of modules from the server using `lsmod` and the result of `modinfo -F signature <module>` for each module?
