### ISSUE TITLE
Disable firewalld when Plesk Firewall is enabled

### ISSUE THREAD

**Issue by stijneikelboom** [plesk/centos2alma#329]
**Is your feature request related to a problem? Please describe.**
AlmaLinux 8 comes with `firewalld` installed and enabled. This conflicts with [Plesk Firewall](https://docs.plesk.com/en-US/obsidian/administrator-guide/plesk-administration/plesk-for-linux-the-plesk-firewall.72046/), rendering rules configured there ineffective.

**Describe the solution you'd like**
Either stop and disable `firewalld` during the conversion, or remove it entirely. Perhaps only do this when Plesk Firewall is enabled. Also restart `fail2ban` if it is installed.

**Describe alternatives you've considered**
Manually stop and disable `firewalld`, and restart Plesk Firewall from the console. See [this KB article](https://support.plesk.com/hc/en-us/articles/12377599139479-The-firewalld-service-reports-the-error-when-the-Plesk-Firewall-is-installed-WARNING-COMMAND-FAILED). However, the order of commands below is favorable to minimize downtime.

Note that these commands should _not_ be run using SSH, as the connection will be temporarily interrupted.

```
sudo systemctl stop firewalld && sudo systemctl restart plesk-firewall.service
sudo systemctl disable firewalld
```

If `fail2ban` is running on the server, manually restart this as well. Stopping `firewalld` also shuts down `fail2ban`.

```
sudo systemctl restart fail2ban
```

**Comment by SandakovMM** [comment]
I have added the option to disable firewalld in #342

**Comment by stijneikelboom** [comment]
Great work! Just wondering if it has been tested to work properly with `fail2ban` as well?

As added later, it turns out that `fail2ban` stops along with `firewalld` on a running server. This may not be an issue when `firewalld` is stopped during the conversion, but it would be good to validate that `fail2ban` keeps working.

**Comment by SandakovMM** [comment]
> Just wondering if it has been tested to work properly with fail2ban as well?

It should work. I see that the fail2ban service is active after the conversion. I also checked if banning an IP manually works, and it is fine.

**Comment by stijneikelboom** [comment]
Thanks for checking! Appreciate knowing that for sure.
