### ISSUE TITLE
Upgrade fails with invalid repomap version

### ISSUE THREAD

**Issue by JandeGrootDuracom** [plesk/centos2alma#351]
The centos2alma script aborts with this message:
The repository mapping file is invalid: The obtained repomap data has unsupported version of format. Get 1.2.0 required 1.2.1

Installed elevate packages:
leapp-0.16.0-2.el7.noarch
leapp-data-almalinux-0.2-15.el7.20230823.noarch
python2-leapp-0.16.0-2.el7.noarch
leapp-deps-0.18.0-1.el7.noarch
leapp-upgrade-el7toel8-deps-0.21.0-2.el7.elevate.2.noarch
leapp-upgrade-el7toel8-0.21.0-2.el7.elevate.2.noarch

The problem occurs because the script installs the latest leapp-upgrade-el7toel8 package together with the outdated leapp-data-almalinux-0.2-15.el7.20230823.noarch package (latest version is 0.4-5.el7.20240827)

**Comment by SandakovMM** [comment]
The problem should be fixed by #352. Also [I've published v.1.4.2](https://github.com/plesk/centos2alma/releases/tag/v1.4.2)
