### ISSUE TITLE
FYI: conflicts with file from package python36-argcomplete + python36-colorama

### ISSUE THREAD

**Issue by abien** [plesk/centos2alma#86]
[leapp-upgrade.log.gz](https://github.com/plesk/centos2alma/files/11341772/leapp-upgrade.log.gz)

Abort due to conflicts with two python36 packages.
```
python36-argcomplete
python36-colorama
```
i removed these packages with rpm -e --nodeps and restarted the process.. It went without erros into the reboot phase.

**Comment by SandakovMM** [comment]
Hello @abien,
Thank you for the information. I have included this package in the list of packages that will be uninstalled before the conversion and reinstalled after it. You can find the related pull request at #91.
