### ISSUE TITLE
GIT Instructions Typo

### ISSUE THREAD

**Issue by gregarios** [plesk/centos2alma#90]
Also these instructions from your repository are not possible for obvious reasons:

**wget https://github.com/plesk/centos2alma/releases/download/v0.1.0/centos2alma-0.1.0.zip
unzip centos2alma.zip**

should be:

**wget https://github.com/plesk/centos2alma/releases/download/v0.1.0/centos2alma-0.1.0.zip
unzip centos2alma-0.1.0.zip**

**Comment by SandakovMM** [comment]
Hello @gregarios 

Thank you for bringing the typo to our attention. I have fixed the issue you reported, and the related pull request can be found at #92.
