### ISSUE TITLE
Update from 18.0.41

### ISSUE THREAD

**Issue by danielbwa** [plesk/centos2alma#94]
I want to use this script but I've noticed My Plesk Version is 18.0.41 and the minimal version to run this script is 18.0.43. The only available update from my Plesk  is 18.0.52 and to get this update I need this script so I can migrate from CentOS 7 to AlmaLinux 8. 

I'm willing to try if this script will also work with Plesk 18.0.41 but otherwise is there a way to perform a upgrade to 18.0.43? 

Thanks!

**Comment by gregarios** [comment]
> The only available update from my Plesk is 18.0.52 and to get this update I need this script so I can migrate from CentOS 7 to AlmaLinux 8.

Why not upgrade your CentOS 7 to Plesk 18.0.52 ?

**Comment by danielbwa** [comment]
> Why not upgrade your CentOS 7 to Plesk 18.0.52 ?

The upgrade to 18.0.52 fails on my server. I was getting the error noted here when I wanted to upgrade to 18.0.50 some weeks ago: https://support.plesk.com/hc/en-us/articles/12376925810455 and the cause is that I should upgrade the OS and so I landed on this script to do it.

**Comment by SandakovMM** [comment]
I believe the upgrade to version 18.0.43 can be accessed by using the 'plesk installer --all-versions' command. At least, I was able to upgrade from version 18.0.45 to 18.0.46 using this method.

**Comment by SandakovMM** [comment]
>  The upgrade to 18.0.52 fails on my server. I was getting the error noted here when I wanted to upgrade to 18.0.50 some weeks ago: https://support.plesk.com/hc/en-us/articles/12376925810455 

Hmm, you got the "( 'CentOS' 'Linux' '8.2.2004' 'x86_64' ) available" error on the plesk update? Maybe installer somehow recognize your OS wrong (CentOS 8 instead of CentOS 7) :thinking:

**Comment by danielbwa** [comment]
I'm on CentOS 7 for sure.

This was the last bit of the error I got last time I've tried to upgrade:

```
python3-pip-9.0.3-8.el7.noarch conflicts with file from package python36u-pip-9.0.1-1.ius.centos7.noarch
file /usr/lib/python3.6/site-packages/pip/vcs/__pycache__/subversion.cpython-36.opt-1.pyc from install of python3-pip-9.0.3-8.el7.noarch conflicts with file from package python36u-pip-9.0.1-1.ius.centos7.noarch
file /usr/lib/python3.6/site-packages/pip/vcs/__pycache__/subversion.cpython-36.pyc from install of python3-pip-9.0.3-8.el7.noarch conflicts with file from package python36u-pip-9.0.1-1.ius.centos7.noarch

Launching component and product checkers...
Downloading file report-update: 0%
Downloading file report-update: 100% was finished.
Downloading file pool/PSA_18.0.50_11079/examiners/py_launcher.sh: 0%
Downloading file pool/PSA_18.0.50_11079/examiners/py_launcher.sh: 100% was finished.
Error: The Yum utility failed to install the required packages.
Attention! Your software might be inoperable.
Visit https://support.plesk.com/ to search for a solution.
```

**Comment by SandakovMM** [comment]
Uh, I see. It seems that you are using python36u-pip from the IUS repository, which conflicts with python3-pip from the EPEL repository A similar issue [was described here](https://github.com/iusrepo/python36/issues/11).
To resolve this, you can try removing python36u-pip and installing python3-pip from the EPEL repository instead. I beleive Plesk update will be fine after it.
