### ISSUE TITLE
EL8 version of epel.repo created as epel.repo.rpmnew

### ISSUE THREAD

**Issue by abien** [plesk/centos2alma#99]
### Problem
EL8 version of `epel.repo` might be created as `epel.repo.rpmnew`. Leaving EL7 `epel.repo` active. Causing the process after the first reboot to be unable to install certain packages.

### Cause
During the elevate process the file `/etc/yum.repos.d/epel.repo` will be replaced by the RPM `epel-release-8`. If the original file `epel-release-7` was prevously modified by the admin, the installation of `epel-release-8` will create `/etc/yum.repos.d/epel.repo.rpmnew`. This is expected behaviour with RPM.

### Suggestion
I think this should be handled by the script. Maybe have RPM force the file or ignore the modifications (or save them before replacing).

**Comment by SandakovMM** [comment]
One possible solution could be to force the usage of the new file and save the old one as a .rpmsave file. What do you think?

**Comment by abien** [comment]
Yes, that would be preferable.
Maybe inform the user at the end of the run about the replacement via the motd.
something like: "### Please note: We have replaced your epel.repo file with the default for EL8. You can find your old/modified file in <...>"

**Comment by SandakovMM** [comment]
Hello @abien
I wanted to inform you that I have merged PR #100, which should address the problem we were facing.
Thank you for your assistance in detecting and resolving it.
